name: Collect
on:
  workflow_dispatch:
  schedule:
    # 建议保持每 6 小时运行一次，或改为每天固定时间
    - cron: '0 */6 * * *'

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt pyyaml

      - name: Run Aggregator
        env:
          GIST_PAT: ${{ secrets.GIST_TOKEN }}
          GIST_LINK: ${{ secrets.GIST_ID }}
        run: |
          # 增量修改：末尾增加了 --all 参数
          # --all 会指示脚本生成包含 URL-Test (自动优选) 策略组的完整 Clash 配置文件
          python subscribe/collect.py -g ${{ secrets.GIST_ID }} -k ${{ secrets.GIST_TOKEN }} -t clash v2ray singbox --skip --all
