name: Collect
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # 必须是3.10，解决你图中的 TypeError

      - name: Install dependencies
        run: pip install -r requirements.txt pyyaml

      - name: Run Aggregator
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        # 暂时去掉 -s 参数，先保证基础运行通畅
        run: python subscribe/collect.py --config config.yaml
