bmFtZTogUmVmcmVzaApvbjoKICAjIHBlcmZvcm1lZCBldmVyeSB0d28gaG91
cnMKICBzY2hlZHVsZToKICAgIC0gY3JvbjogIjAgKi8yICogKiAqIgogIHdv
cmtmbG93X2Rpc3BhdGNoOgoKY29uY3VycmVuY3k6CiAgZ3JvdXA6ICR7eyBn
aXRodWIucmVwb3NpdG9yeSB9fQogIGNhbmNlbC1pbi1wcm9ncmVzczogdHJ1
ZQoKZW52OgogICMgdGltZSB6b25lCiAgVFo6IEFzaWEvU2hhbmdoYWkKCiAg
IyBnaXRodWIgYWNjZXNzIHRva2VuCiAgR0lTVF9QQVQ6ICR7eyBzZWNyZXRz
LkdJU1RfUEFUIH19CgogICMgZ2l0aHViIHVzZXJuYW1lIGFuZCBnaXN0IGlk
LCBzZXBhcmF0ZWQgYnkgJy8nCiAgR0lTVF9MSU5LOiAke3sgc2VjcmV0cy5H
SVNUX0xJTksgfX0KCiAgIyB0aGUgdXJsIHRvIHRoZSBsaXN0IG9mIGFpcnBv
cnRzIHRoYXQgeW91IG1haW50YWluIHlvdXJzZWxmCiAgIyBlYWNoIGxpbmUg
aW5jbHVkZSBkb21haW4sIGNvdXBvbiBhbmQgaW52aXRhdGlvbiBjb2RlLCB0
aGUgZG9tYWluIG11c3QgYmUgaW5jbHVkZWQsIGFuZCB0aGUgbGF0dGVyIHR3
byBpdGVtcyBhcmUgb3B0aW9uYWwKICBDVVNUT01JWkVfTElOSzogJHt7IHNl
Y3JldHMuQ1VTVE9NSVpFX0xJTksgfX0KCiAgIyBpbmNsdWRlIHNwZWNpYWwg
cHJvdG9jb2xzLCBzdWNoIGFzIHZsZXNzIGh5c3RlcmlhMiBhbmQgaHlzdGVy
aWEKICBFTkFCTEVfU1BFQ0lBTF9QUk9UT0NPTFM6ICR7eyB2YXJzLkVOQUJM
RV9TUEVDSUFMX1BST1RPQ09MUyB9fQoKam9iczoKICBwcm9jZXNzOgogICAg
cnVucy1vbjogdWJ1bnR1LWxhdGVzdAoKICAgIHN0ZXBzOgogICAgICAtIG5h
bWU6IENoZWNrb3V0CiAgICAgICAgdXNlczogYWN0aW9ucy9jaGVja291dEB2
NAogICAgICAgIHdpdGg6CiAgICAgICAgICByZWY6IG1haW4KCiAgICAgIC0g
bmFtZTogUHJlcGFyZQogICAgICAgIHVzZXM6IGFjdGlvbnMvc2V0dXAtcHl0
aG9uQHY1CiAgICAgICAgd2l0aDoKICAgICAgICAgIHB5dGhvbi12ZXJzaW9u
OiAiMy54IgogICAgICAgICAgYXJjaGl0ZWN0dXJlOiAieDY0IgogICAgICAg
ICAgY2FjaGU6ICJwaXAiCgogICAgICAtIG5hbWU6IEluc3RhbGwKICAgICAg
ICBydW46IHBpcDMgaW5zdGFsbCAtciByZXF1aXJlbWVudHMudHh0CgogICAg
ICAtIG5hbWU6IENoZWNrCiAgICAgICAgcnVuOiB8CiAgICAgICAgICBpZiBb
IC16ICIkR0lTVF9QQVQiIF07IHRoZW4KICAgICAgICAgICAgICBlY2hvICJF
cnJvcjogZW52aXJvbm1lbnQgJ0dJU1RfUEFUJyBjYW5ub3QgYmUgZW1wdHki
CiAgICAgICAgICAgICAgZXhpdCAxCiAgICAgICAgICBmaQoKICAgICAgICAg
IGlmIFsgLXogIiRHSVNUX0xJTksiIF07IHRoZW4KICAgICAgICAgICAgICBl
Y2hvICJFcnJvcjogZW52aXJvbm1lbnQgJ0dJU1RfTElOSycgY2Fubm90IGJl
IGVtcHR5IgogICAgICAgICAgICAgIGV4aXQgMQogICAgICAgICAgZmkKCiAg
ICAgICAgICBMSU5LX1BBUlRTPSQoZWNobyAiJEdJU1RfTElOSyIgfCBhd2sg
LUYnLycgJ05GPT0yICYmICQxIT0iIiAmJiAkMiE9IiInKQogICAgICAgICAg
aWYgWyAteiAiJExJTktfUEFSVFMiIF07IHRoZW4KICAgICAgICAgICAgICBl
Y2hvICJFcnJvcjogZW52aXJvbm1lbnQgJ0dJU1RfTElOSycgaXMgbm90IHZh
bGlkLCBzaG91bGQgYmUgJ3VzZXJuYW1lL2dpc3RfaWQnIGZvcm1hdCIKICAg
ICAgICAgICAgICBleGl0IDEKICAgICAgICAgIGZpCgogICAgICAtIG5hbWU6
IFJlZnJlc2gKICAgICAgICBydW46IHB5dGhvbiAtdSBzdWJzY3JpYmUvY29s
bGVjdC5weSAtLWFsbCAtLXJlZnJlc2ggLS1vdmVyd3JpdGUgLS1za2lwCgog
ICAgICAtIG5hbWU6IFRpbWVzdGFtcAogICAgICAgIHJ1bjogZGF0ZQo=
